### ISSUE TITLE
shell.openExternal

### ISSUE THREAD

**Issue by sethvincent** [bcomnes/choo-location-electron#3]
not sure if this needs to be included in this module, but something that came up for me was needing to open up all external urls in the default OS browser. So I revised the subscription to look like this:

``` js
var shell = require('electron').shell

function catchLinks (send, done) {
  window.onclick = function (e) {
    e.preventDefault()
    var node = (function traverse (node) {
      if (!node) return
      if (node.localName !== 'a') return traverse(node.parentNode)
      if (node.href === undefined) return traverse(node.parentNode)
      return node
    })(e.target)

    if (!node || !node.href) return
    e.preventDefault()
    if (node.href.indexOf('http') > -1) {
      return shell.openExternal(node.href)
    }
    var href = node.href.replace('file://', '')
    send('location:redirect', href.replace(/#$/, ''), done)
  }
}
```

Most notable is using `shell.openExternal`:

``` js
 if (node.href.indexOf('http') > -1) {
  return shell.openExternal(node.href)
}
```

I can imagine cases where this behavior wouldn't be useful, so not sure how/if it might be included in this module.

**Comment by bcomnes** [comment]
Maybe make it an optional option?  I'm open to adding some options

**Comment by sethvincent** [comment]
Yeah, something like this?

``` js
var location = require('choo-location-electron')

app.model(location({ openExternal: true })
```

Then instead of exporting an object this module would have to export a function that takes an `options` object.

I could make a PR for this if you like.

**Comment by bcomnes** [comment]
Yeah that would be great!  Happy to review.  IIRC you have push and publish rights too.   This would be a major version bump it seems.

**Comment by bcomnes** [comment]
Published in v.2.0.0 https://www.npmjs.com/package/choo-location-electron
