### ISSUE TITLE
Choo supports electron out of the box now

### ISSUE THREAD

**Issue by rahatarmanahmed** [bcomnes/choo-location-electron#7]
As of v4 choo is supposed to work in electron out of the box without any plugins. It might be helpful to add some kind of notice in the README saying that so users don't get confused?

**Comment by bcomnes** [comment]
There are some issues with the built in routing with electron last I was messing around with it.  See https://github.com/hypermodules/hyperamp/issues/68

Depending on how it gets resolved upstream in sheet-router, it may obviate the need for this module, but we may also just fix this and make it an alternative to the default routing that ships with choo (if it provides any advantage).  This module potentially affords us more room to deal with electron weirdness that upstream might not want.  With this approach, routing and refresh worked perfectly in choo 3.  In choo 4, routing works, but refresh doesn't and it looks like it might have to do with some oddities around how window.location works with file loading in electron.

 I guess we could put a little warning in the README to clarify uncertainty of things right now.

**Comment by bcomnes** [comment]
Choo 5 uses nanorouter and hash based routing works great.  Closing.
